### ISSUE TITLE
bindgen usage for boring-sys

### ISSUE THREAD

**Issue by jedisct1** [cloudflare/boring#10]
Hi,

And thanks for these crates!

The BoringSSL revision is constantly kept up to date, which is really neat. However, declarations from `boring-sys` are running behind the BoringSSL API changes.

Could it be an option to use `bindgen` for `boring-sys` in order to automatically keep the external declarations in sync with the BoringSSL API?

This is something I can contribute, but maybe there is a reason why bindings seem to be manually maintained rather than leveraging `bindgen`.

Thanks!

**Comment by inikulin** [comment]
Hi, thank you!

The project has started as a fork of rust-openssl, which supports few different versions of OpenSSL and LibreSSL, so it was impossible to use bindgen there. However, as you pointed, we aim to provide API only for latest BoringSSL version and, hence, bindgen-based approach will work for us. PRs are welcome 😃

**Comment by nox** [comment]
I think this can be closed.

**Comment by inikulin** [comment]
Implemented in https://github.com/cloudflare/boring/pull/11
