### ISSUE TITLE
boring-sys compile failed on windows

### ISSUE THREAD

**Issue by Lsyx-Good** [cloudflare/boring#242]
boring-sys compile failed when set env **CMAKE_GENERATOR = Ninja** , crypto library exist on compiler output path, but search library path is  incorrect, for [msvc targets](https://github.com/cloudflare/boring/blob/b3eaacc33a040597e1b2bf45008927f8a368ac6e/boring-sys/build/main.rs#L156) it adds debug/RelWithDebInfo/Release to the library path, which is wrong for CMAKE_GENERATOR as Ninja.

![image](https://github.com/cloudflare/boring/assets/59752988/19ddcb9f-11ed-4c9e-8e76-969b508faa6b)

![image](https://github.com/cloudflare/boring/assets/59752988/34ed67f5-b85c-4b09-bbf2-f6d2b9329f6e)

![image](https://github.com/cloudflare/boring/assets/59752988/702cbb6f-aeab-4972-a222-34c9d7e83b22)

**Comment by PaulDance** [comment]
This is what #223 aims to fix, although it probably needs to be updated. It's at least a good sign that it does not happen only to us.
