### ISSUE TITLE
boring: Unable to set curves

### ISSUE THREAD

**Issue by 0x676e67** [cloudflare/boring#257]
Branch: master

Test Code:

```rust
#[test]
fn set_curves() {
    let mut ctx = SslContext::builder(SslMethod::tls()).unwrap();
    ctx.set_curves(&[SslCurve::SECP224R1, SslCurve::SECP256R1])
        .unwrap();
}
```

Output:
```log
---- ssl::test::set_curves stdout ----
thread 'ssl::test::set_curves' panicked at boring/src/ssl/test/mod.rs:545:10:
called `Result::unwrap()` on an `Err` value: ErrorStack([])
```

**Comment by rushilmehra** [comment]
Almost certainly related to https://github.com/cloudflare/boring/commit/0e33475b936e19671d4239b6722e51784214ea5b. I'll take a look soon

**Comment by 0x676e67** [comment]
> Almost certainly related to [0e33475](https://github.com/cloudflare/boring/commit/0e33475b936e19671d4239b6722e51784214ea5b). I'll take a look soon

thank you for your reply

**Comment by 0x676e67** [comment]
The test is normal in 4.8.0, it seems that the problem is indeed here https://github.com/cloudflare/boring/commit/0e33475b936e19671d4239b6722e51784214ea5b

**Comment by rushilmehra** [comment]
Will take a look as soon as I'm home - apologies for breaking your code
