### ISSUE TITLE
How to create a DTLS SSL Stream from an UDP socket

### ISSUE THREAD

**Issue by rainerschoe** [cloudflare/boring#35]
Hi,

I want to create a DTLS session via UDP. However I cannot find out how to instantiate the SSL stream.
I tried to modify the `boring tcp` example:
```
    println!("Hello, world!");
    let connector = SslConnector::builder(SslMethod::dtls()).unwrap().build();

    let socket = UdpSocket::bind("127.0.0.1:3400").expect("couldn't bind to address");
    socket.connect("127.0.0.1:8080").expect("connect function failed");

    let mut stream = connector.connect("google.com", socket).unwrap();
```

This fails, as `UdpSocket` is not implementing `Read` and `Write` traits, which are required by `SslConnector.connect`.

Do I have to implement those traits myself, or is there another method to instantiate the SSL stream?

**Comment by jyn514** [comment]
Hmm, this seems like it should be an upstream request to the standard library - it seems reasonable for `UdpSocket` to implement Read and Write, I don't know why it doesn't.

**Comment by rainerschoe** [comment]
Thanks for the reply. By now i implemented a wrapper for UdpSocket which implements read/write.
On client side this is fairly straight forward, however on server side this is messy, as UdpSockets do not have the concept of connections. So extra work is needed for dispatching packets to the correct SSL stream in case multiple clients connect.

I think the this difference to TCP sockets might be the reason why read/write is not implemented in UdpSocket by default :)
