### ISSUE TITLE
Support pre-built binaries of BoringSSL

### ISSUE THREAD

**Issue by Evrard-Nil** [cloudflare/boring#36]
Hi all, this is a proposition for an enhancement. 

When using this crate as part of a large project, users may have a build system already building BoringSSL and want to rely on it instead of building it multiple times. This happened to us and thought that others may have the same need.

This feature would allow users to specify a path to the pre-built binaries and one for the corresponding headers in case the version is not the same. It could be done using environment variables which would be checked during the build in boring-sys. Default behavior would stay the same.

**Comment by jyn514** [comment]
Added in https://github.com/cloudflare/boring/pull/37.
