### ISSUE TITLE
Add support for `X509StoreContextRef::chain` under FIPS mode

### ISSUE THREAD

**Issue by jyn514** [cloudflare/boring#66]
Right now it's feature gated: https://github.com/cloudflare/boring/blob/1507689c5b49fa732cbf54f59e998116fab79287/boring/src/x509/mod.rs#L200-L208
The fips-compatible version of `X509_STORE_CTX_get0_chain` is `X509_STORE_CTX_get1_chain`.

**Comment by nox** [comment]
This is no longer gated by fips
